"use client";

import { motion } from "framer-motion";
import { DetectionResult } from "@/types";
import GaugeMeter from "./GaugeMeter";

interface ResultCardProps {
  result: DetectionResult;
  onReset: () => void;
}

export default function ResultCard({ result, onReset }: ResultCardProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 24, scale: 0.96 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      transition={{ duration: 0.5, ease: "easeOut" }}
      className="glow-card relative z-10 mx-auto mt-8 w-full max-w-md rounded-3xl border border-white/10 bg-surface/60 p-8 backdrop-blur-xl md:p-10"
    >
      <GaugeMeter
        confidence={result.confidence}
        prediction={result.prediction}
      />

      <div className="mt-8 space-y-3 border-t border-white/10 pt-6 text-sm text-muted">
        <div className="flex justify-between">
          <span>Model status</span>
          <span className="font-[family-name:var(--font-code)] text-accent">
            LOADED
          </span>
        </div>
        <div className="flex justify-between">
          <span>Frames analyzed</span>
          <span className="font-[family-name:var(--font-code)] text-foreground">
            10
          </span>
        </div>
        <div className="flex justify-between">
          <span>Inference time</span>
          <span className="font-[family-name:var(--font-code)] text-foreground">
            ~10-15s
          </span>
        </div>
      </div>

      <p className="mt-6 text-center text-xs leading-5 text-muted/70">
        Prediction is generated by our model by frames analyzing.
      </p>

      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={onReset}
        className="mt-6 w-full rounded-xl border border-white/10 bg-white/5 py-3 text-sm font-semibold uppercase tracking-wider text-foreground transition-colors hover:bg-white/10"
      >
        Analyze Another Video
      </motion.button>
    </motion.div>
  );
}
